title: Visual Computing Conference Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to top CG/CV/VIS/ML/Robotics/AI conference deadlines
author: Abhishek Das

domain: "ddl.vcc.tech"
baseurl: ""

host                : 0.0.0.0
port                : 8001

twitter_username: qheldiv
twitter_hashtag: computergraphics
github_username: vcc-szu
github_repo: visual-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
